#:schema node_modules/wrangler/config-schema.json
name = "talesandpages"
compatibility_date = "2024-09-03"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DATABASE"
database_name = "lucky-firefly-9cbd-db"
database_id = "e193f2c8-ea3a-4b95-acd4-bcd1e5d10d36"

[ai]
binding = "AI"
model_name = "llama-3-8b-instruct"





